<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Persistence.Mongo\Persistence.Mongo.csproj" />
    <ProjectReference Include="..\Common\Collections.Common.csproj" />
  </ItemGroup>

</Project>
