<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Implementation\Implementation.csproj" />
    <ProjectReference Include="..\Common\Configuration.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Runtime/" />
  </ItemGroup>

</Project>
