version: "3"

vars:

tasks:
  l10n:generate:
    aliases: [gen-l10n]
    cmds:
      - flutter gen-l10n --arb-dir ./lib/ui/core/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class CoreLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/auth/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class AuthLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/chat/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class ChatLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/dashboard/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class DashboardLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/events/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class EventsLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/organizers/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class OrganizersLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/participants/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class ParticipantsLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/profile/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class ProfileLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/registrations/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class RegistrationsLocalizations
      - flutter gen-l10n --arb-dir ./lib/ui/sites/l10n --template-arb-file en.arb --output-localization-file localizations.dart --output-class SitesLocalizations
    desc: "Generate localization files"

# build: update taskfile.yaml for iOS app validation and upload
# - Added commented commands for validating and uploading iOS app using xcrun altool
# dart run build_runner build
# xcrun altool --validate-app --type ios -f build/ios/ipa/*.ipa --apiKey G6HZU7K2U2 --apiIssuer 5e592804-e7ba-4d8c-b341-a66644f74744
# xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey G6HZU7K2U2 --apiIssuer 5e592804-e7ba-4d8c-b341-a66644f74744
