// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt3AT3y9mABh_MrWkSpTKQlH4UQYlnr2A',
    appId: '1:875409099173:web:ac25801e49405ca795404c',
    messagingSenderId: '875409099173',
    projectId: 'hot-knobs-dev',
    authDomain: 'hot-knobs-dev.firebaseapp.com',
    storageBucket: 'hot-knobs-dev.firebasestorage.app',
    measurementId: 'G-NX3196GY2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHM0j5CgArfPLdKWbphr-6gRjbwSYdEc',
    appId: '1:875409099173:android:feeddaa12b20c3bf95404c',
    messagingSenderId: '875409099173',
    projectId: 'hot-knobs-dev',
    storageBucket: 'hot-knobs-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzjcfj1NMaRk3HQxWZtGHTc_HAbb-4Gk',
    appId: '1:875409099173:ios:732db523d4e20a3395404c',
    messagingSenderId: '875409099173',
    projectId: 'hot-knobs-dev',
    storageBucket: 'hot-knobs-dev.firebasestorage.app',
    iosClientId: '875409099173-08kleuibddpvos3a223lgqjq97cp2g1v.apps.googleusercontent.com',
    iosBundleId: 'app.hotknobs.v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzjcfj1NMaRk3HQxWZtGHTc_HAbb-4Gk',
    appId: '1:875409099173:ios:9d6f4df9f2dc5fb495404c',
    messagingSenderId: '875409099173',
    projectId: 'hot-knobs-dev',
    storageBucket: 'hot-knobs-dev.firebasestorage.app',
    iosClientId: '875409099173-08kleuibddpvos3a223lgqjq97cp2g1v.apps.googleusercontent.com',
    iosBundleId: 'app.hotknobs.v1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt3AT3y9mABh_MrWkSpTKQlH4UQYlnr2A',
    appId: '1:875409099173:web:77d219ca0380301695404c',
    messagingSenderId: '875409099173',
    projectId: 'hot-knobs-dev',
    authDomain: 'hot-knobs-dev.firebaseapp.com',
    storageBucket: 'hot-knobs-dev.firebasestorage.app',
    measurementId: 'G-Q4LGNVHLJS',
  );
}
