<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Persistence.Postgres\Persistence.Postgres.csproj" />
    <ProjectReference Include="..\Common\Dummy.Common.csproj" />
  </ItemGroup>

</Project>
