<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <!-- Naming convention -->
  <PropertyGroup>
    <DefaultAssemblyName>$(DefaultAssemblyName).Domains.$(MSBuildProjectName)</DefaultAssemblyName>
	  <DefaultRootNamespace>$(DefaultRootNamespace).Domains</DefaultRootNamespace>

    <ArtifactsProjectName>Domains.$(MSBuildProjectName)</ArtifactsProjectName>
  </PropertyGroup>

</Project>
