<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace).AzureBlobStorage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />

    <ProjectReference Include="..\..\Common.Tests\Common.Tests.csproj" />
    <ProjectReference Include="..\AzureBlobStorage\Storage.AzureBlobStorage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
