//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thc.HotKnobs.Runtime.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages_cs_CZ {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_cs_CZ() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("thc.HotKnobs.Runtime.Resources.ErrorMessages.cs-CZ", typeof(ErrorMessages_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Požadavek se nezdařil.
        /// </summary>
        public static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vyžadováno přihlášení.
        /// </summary>
        public static string _401 {
            get {
                return ResourceManager.GetString("401", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Přístup odepřen.
        /// </summary>
        public static string _403 {
            get {
                return ResourceManager.GetString("403", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nenalezeno.
        /// </summary>
        public static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dochází ke konfliktu.
        /// </summary>
        public static string _409 {
            get {
                return ResourceManager.GetString("409", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Odstraněno.
        /// </summary>
        public static string _410 {
            get {
                return ResourceManager.GetString("410", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nesplněný předpoklad.
        /// </summary>
        public static string _412 {
            get {
                return ResourceManager.GetString("412", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Požadována podmínka.
        /// </summary>
        public static string _428 {
            get {
                return ResourceManager.GetString("428", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chyba serveru.
        /// </summary>
        public static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Není podporováno.
        /// </summary>
        public static string _501 {
            get {
                return ResourceManager.GetString("501", resourceCulture);
            }
        }
    }
}
