<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace).Mapster</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" />

    <ProjectReference Include="..\..\Common\Common.csproj" />
  </ItemGroup>

</Project>
