<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Fand.Runtime.Common" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Runtime\Configuration\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Runtime\Configuration\ServiceConfiguration.cs" />
  </ItemGroup>

</Project>
