name: thc-hotknobs

include:
  - ../docker-compose.yaml

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    container_name: thc-hotknobs-dev
    hostname: dev
    networks:
      - default
    volumes:
      - ../..:/workspaces:cached
      - ../../.npmrc:/home/vscode/.npmrc:cached
      - ../../NuGet.Config:/home/vscode/.nuget/NuGet/NuGet.Config:cached
