<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);ANONYMOUS</DefineConstants>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace).Server</RootNamespace>

    <IsPublishable>true</IsPublishable>

    <UserSecretsId>57a4c852-5ffe-4484-b4de-34ff0148ad8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ErrorMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorMessages.cs-CZ.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessages.cs-CZ.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ErrorMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ErrorMessages.cs-CZ.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorMessages.cs-CZ.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Runtime.Server\Runtime.Server.csproj" />
    <ProjectReference Include="..\Contracts\Dummy.Contracts.csproj" />
    <ProjectReference Include="..\Implementation\Dummy.Implementation.csproj" />
    <ProjectReference Include="..\Persistence.Cosmos\Dummy.Persistence.Cosmos.csproj" />
    <ProjectReference Include="..\Persistence.Mongo\Dummy.Persistence.Mongo.csproj" />
    <ProjectReference Include="..\Persistence.Postgres\Dummy.Persistence.Postgres.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- <PackageReference Include="Fand.Runtime.Queues.AzureStorageAccount" /> -->
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" />
  </ItemGroup>

</Project>
