<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.EntityFrameworkCore" />

    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
