/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignUpImport } from './routes/_auth/signUp'
import { Route as AuthSignInImport } from './routes/_auth/signIn'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgotPassword'
import { Route as AuthChangePasswordImport } from './routes/_auth/changePassword'
import { Route as AppDashboardImport } from './routes/_app/dashboard'
import { Route as AppAdminImport } from './routes/_app/admin'
import { Route as AppAdminSitesIndexImport } from './routes/_app/admin/sites/index'
import { Route as AppAdminRidersIndexImport } from './routes/_app/admin/riders/index'
import { Route as AppAdminOperatorsIndexImport } from './routes/_app/admin/operators/index'
import { Route as AppAdminCoachesIndexImport } from './routes/_app/admin/coaches/index'
import { Route as AppAdminSitesNewImport } from './routes/_app/admin/sites/new'
import { Route as AppAdminSitesIdImport } from './routes/_app/admin/sites/$id'
import { Route as AppAdminRidersNewImport } from './routes/_app/admin/riders/new'
import { Route as AppAdminRidersIdImport } from './routes/_app/admin/riders/$id'
import { Route as AppAdminOperatorsNewImport } from './routes/_app/admin/operators/new'
import { Route as AppAdminCoachesNewImport } from './routes/_app/admin/coaches/new'
import { Route as AppAdminSitesIdViewImport } from './routes/_app/admin/sites/$id.view'
import { Route as AppAdminRidersIdViewImport } from './routes/_app/admin/riders/$id.view'
import { Route as AppAdminOperatorsIdViewImport } from './routes/_app/admin/operators/$id.view'
import { Route as AppAdminOperatorsIdEditImport } from './routes/_app/admin/operators/$id.edit'
import { Route as AppAdminCoachesIdEditImport } from './routes/_app/admin/coaches/$id.edit'
import { Route as AppAdminCoachesDViewImport } from './routes/_app/admin/coaches/$d.view'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/_auth/signUp',
  path: '/signUp',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/_auth/signIn',
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/_auth/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRoute,
} as any)

const AuthChangePasswordRoute = AuthChangePasswordImport.update({
  id: '/_auth/changePassword',
  path: '/changePassword',
  getParentRoute: () => rootRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppAdminRoute = AppAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

const AppAdminSitesIndexRoute = AppAdminSitesIndexImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminRidersIndexRoute = AppAdminRidersIndexImport.update({
  id: '/riders/',
  path: '/riders/',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminOperatorsIndexRoute = AppAdminOperatorsIndexImport.update({
  id: '/operators/',
  path: '/operators/',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminCoachesIndexRoute = AppAdminCoachesIndexImport.update({
  id: '/coaches/',
  path: '/coaches/',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminSitesNewRoute = AppAdminSitesNewImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminSitesIdRoute = AppAdminSitesIdImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminRidersNewRoute = AppAdminRidersNewImport.update({
  id: '/riders/new',
  path: '/riders/new',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminRidersIdRoute = AppAdminRidersIdImport.update({
  id: '/riders/$id',
  path: '/riders/$id',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminOperatorsNewRoute = AppAdminOperatorsNewImport.update({
  id: '/operators/new',
  path: '/operators/new',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminCoachesNewRoute = AppAdminCoachesNewImport.update({
  id: '/coaches/new',
  path: '/coaches/new',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminSitesIdViewRoute = AppAdminSitesIdViewImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AppAdminSitesIdRoute,
} as any)

const AppAdminRidersIdViewRoute = AppAdminRidersIdViewImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AppAdminRidersIdRoute,
} as any)

const AppAdminOperatorsIdViewRoute = AppAdminOperatorsIdViewImport.update({
  id: '/operators/$id/view',
  path: '/operators/$id/view',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminOperatorsIdEditRoute = AppAdminOperatorsIdEditImport.update({
  id: '/operators/$id/edit',
  path: '/operators/$id/edit',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminCoachesIdEditRoute = AppAdminCoachesIdEditImport.update({
  id: '/coaches/$id/edit',
  path: '/coaches/$id/edit',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAdminCoachesDViewRoute = AppAdminCoachesDViewImport.update({
  id: '/coaches/$d/view',
  path: '/coaches/$d/view',
  getParentRoute: () => AppAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_auth/changePassword': {
      id: '/_auth/changePassword'
      path: '/changePassword'
      fullPath: '/changePassword'
      preLoaderRoute: typeof AuthChangePasswordImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgotPassword': {
      id: '/_auth/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_auth/signIn': {
      id: '/_auth/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/_auth/signUp': {
      id: '/_auth/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/_app/admin/coaches/new': {
      id: '/_app/admin/coaches/new'
      path: '/coaches/new'
      fullPath: '/admin/coaches/new'
      preLoaderRoute: typeof AppAdminCoachesNewImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/operators/new': {
      id: '/_app/admin/operators/new'
      path: '/operators/new'
      fullPath: '/admin/operators/new'
      preLoaderRoute: typeof AppAdminOperatorsNewImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/riders/$id': {
      id: '/_app/admin/riders/$id'
      path: '/riders/$id'
      fullPath: '/admin/riders/$id'
      preLoaderRoute: typeof AppAdminRidersIdImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/riders/new': {
      id: '/_app/admin/riders/new'
      path: '/riders/new'
      fullPath: '/admin/riders/new'
      preLoaderRoute: typeof AppAdminRidersNewImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/sites/$id': {
      id: '/_app/admin/sites/$id'
      path: '/sites/$id'
      fullPath: '/admin/sites/$id'
      preLoaderRoute: typeof AppAdminSitesIdImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/sites/new': {
      id: '/_app/admin/sites/new'
      path: '/sites/new'
      fullPath: '/admin/sites/new'
      preLoaderRoute: typeof AppAdminSitesNewImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/coaches/': {
      id: '/_app/admin/coaches/'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AppAdminCoachesIndexImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/operators/': {
      id: '/_app/admin/operators/'
      path: '/operators'
      fullPath: '/admin/operators'
      preLoaderRoute: typeof AppAdminOperatorsIndexImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/riders/': {
      id: '/_app/admin/riders/'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AppAdminRidersIndexImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/sites/': {
      id: '/_app/admin/sites/'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AppAdminSitesIndexImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/coaches/$d/view': {
      id: '/_app/admin/coaches/$d/view'
      path: '/coaches/$d/view'
      fullPath: '/admin/coaches/$d/view'
      preLoaderRoute: typeof AppAdminCoachesDViewImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/coaches/$id/edit': {
      id: '/_app/admin/coaches/$id/edit'
      path: '/coaches/$id/edit'
      fullPath: '/admin/coaches/$id/edit'
      preLoaderRoute: typeof AppAdminCoachesIdEditImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/operators/$id/edit': {
      id: '/_app/admin/operators/$id/edit'
      path: '/operators/$id/edit'
      fullPath: '/admin/operators/$id/edit'
      preLoaderRoute: typeof AppAdminOperatorsIdEditImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/operators/$id/view': {
      id: '/_app/admin/operators/$id/view'
      path: '/operators/$id/view'
      fullPath: '/admin/operators/$id/view'
      preLoaderRoute: typeof AppAdminOperatorsIdViewImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/admin/riders/$id/view': {
      id: '/_app/admin/riders/$id/view'
      path: '/view'
      fullPath: '/admin/riders/$id/view'
      preLoaderRoute: typeof AppAdminRidersIdViewImport
      parentRoute: typeof AppAdminRidersIdImport
    }
    '/_app/admin/sites/$id/view': {
      id: '/_app/admin/sites/$id/view'
      path: '/view'
      fullPath: '/admin/sites/$id/view'
      preLoaderRoute: typeof AppAdminSitesIdViewImport
      parentRoute: typeof AppAdminSitesIdImport
    }
  }
}

// Create and export the route tree

interface AppAdminRidersIdRouteChildren {
  AppAdminRidersIdViewRoute: typeof AppAdminRidersIdViewRoute
}

const AppAdminRidersIdRouteChildren: AppAdminRidersIdRouteChildren = {
  AppAdminRidersIdViewRoute: AppAdminRidersIdViewRoute,
}

const AppAdminRidersIdRouteWithChildren =
  AppAdminRidersIdRoute._addFileChildren(AppAdminRidersIdRouteChildren)

interface AppAdminSitesIdRouteChildren {
  AppAdminSitesIdViewRoute: typeof AppAdminSitesIdViewRoute
}

const AppAdminSitesIdRouteChildren: AppAdminSitesIdRouteChildren = {
  AppAdminSitesIdViewRoute: AppAdminSitesIdViewRoute,
}

const AppAdminSitesIdRouteWithChildren = AppAdminSitesIdRoute._addFileChildren(
  AppAdminSitesIdRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminCoachesNewRoute: typeof AppAdminCoachesNewRoute
  AppAdminOperatorsNewRoute: typeof AppAdminOperatorsNewRoute
  AppAdminRidersIdRoute: typeof AppAdminRidersIdRouteWithChildren
  AppAdminRidersNewRoute: typeof AppAdminRidersNewRoute
  AppAdminSitesIdRoute: typeof AppAdminSitesIdRouteWithChildren
  AppAdminSitesNewRoute: typeof AppAdminSitesNewRoute
  AppAdminCoachesIndexRoute: typeof AppAdminCoachesIndexRoute
  AppAdminOperatorsIndexRoute: typeof AppAdminOperatorsIndexRoute
  AppAdminRidersIndexRoute: typeof AppAdminRidersIndexRoute
  AppAdminSitesIndexRoute: typeof AppAdminSitesIndexRoute
  AppAdminCoachesDViewRoute: typeof AppAdminCoachesDViewRoute
  AppAdminCoachesIdEditRoute: typeof AppAdminCoachesIdEditRoute
  AppAdminOperatorsIdEditRoute: typeof AppAdminOperatorsIdEditRoute
  AppAdminOperatorsIdViewRoute: typeof AppAdminOperatorsIdViewRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminCoachesNewRoute: AppAdminCoachesNewRoute,
  AppAdminOperatorsNewRoute: AppAdminOperatorsNewRoute,
  AppAdminRidersIdRoute: AppAdminRidersIdRouteWithChildren,
  AppAdminRidersNewRoute: AppAdminRidersNewRoute,
  AppAdminSitesIdRoute: AppAdminSitesIdRouteWithChildren,
  AppAdminSitesNewRoute: AppAdminSitesNewRoute,
  AppAdminCoachesIndexRoute: AppAdminCoachesIndexRoute,
  AppAdminOperatorsIndexRoute: AppAdminOperatorsIndexRoute,
  AppAdminRidersIndexRoute: AppAdminRidersIndexRoute,
  AppAdminSitesIndexRoute: AppAdminSitesIndexRoute,
  AppAdminCoachesDViewRoute: AppAdminCoachesDViewRoute,
  AppAdminCoachesIdEditRoute: AppAdminCoachesIdEditRoute,
  AppAdminOperatorsIdEditRoute: AppAdminOperatorsIdEditRoute,
  AppAdminOperatorsIdViewRoute: AppAdminOperatorsIdViewRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/changePassword': typeof AuthChangePasswordRoute
  '/forgotPassword': typeof AuthForgotPasswordRoute
  '/signIn': typeof AuthSignInRoute
  '/signUp': typeof AuthSignUpRoute
  '/admin/coaches/new': typeof AppAdminCoachesNewRoute
  '/admin/operators/new': typeof AppAdminOperatorsNewRoute
  '/admin/riders/$id': typeof AppAdminRidersIdRouteWithChildren
  '/admin/riders/new': typeof AppAdminRidersNewRoute
  '/admin/sites/$id': typeof AppAdminSitesIdRouteWithChildren
  '/admin/sites/new': typeof AppAdminSitesNewRoute
  '/admin/coaches': typeof AppAdminCoachesIndexRoute
  '/admin/operators': typeof AppAdminOperatorsIndexRoute
  '/admin/riders': typeof AppAdminRidersIndexRoute
  '/admin/sites': typeof AppAdminSitesIndexRoute
  '/admin/coaches/$d/view': typeof AppAdminCoachesDViewRoute
  '/admin/coaches/$id/edit': typeof AppAdminCoachesIdEditRoute
  '/admin/operators/$id/edit': typeof AppAdminOperatorsIdEditRoute
  '/admin/operators/$id/view': typeof AppAdminOperatorsIdViewRoute
  '/admin/riders/$id/view': typeof AppAdminRidersIdViewRoute
  '/admin/sites/$id/view': typeof AppAdminSitesIdViewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/changePassword': typeof AuthChangePasswordRoute
  '/forgotPassword': typeof AuthForgotPasswordRoute
  '/signIn': typeof AuthSignInRoute
  '/signUp': typeof AuthSignUpRoute
  '/admin/coaches/new': typeof AppAdminCoachesNewRoute
  '/admin/operators/new': typeof AppAdminOperatorsNewRoute
  '/admin/riders/$id': typeof AppAdminRidersIdRouteWithChildren
  '/admin/riders/new': typeof AppAdminRidersNewRoute
  '/admin/sites/$id': typeof AppAdminSitesIdRouteWithChildren
  '/admin/sites/new': typeof AppAdminSitesNewRoute
  '/admin/coaches': typeof AppAdminCoachesIndexRoute
  '/admin/operators': typeof AppAdminOperatorsIndexRoute
  '/admin/riders': typeof AppAdminRidersIndexRoute
  '/admin/sites': typeof AppAdminSitesIndexRoute
  '/admin/coaches/$d/view': typeof AppAdminCoachesDViewRoute
  '/admin/coaches/$id/edit': typeof AppAdminCoachesIdEditRoute
  '/admin/operators/$id/edit': typeof AppAdminOperatorsIdEditRoute
  '/admin/operators/$id/view': typeof AppAdminOperatorsIdViewRoute
  '/admin/riders/$id/view': typeof AppAdminRidersIdViewRoute
  '/admin/sites/$id/view': typeof AppAdminSitesIdViewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/changePassword': typeof AuthChangePasswordRoute
  '/_auth/forgotPassword': typeof AuthForgotPasswordRoute
  '/_auth/signIn': typeof AuthSignInRoute
  '/_auth/signUp': typeof AuthSignUpRoute
  '/_app/admin/coaches/new': typeof AppAdminCoachesNewRoute
  '/_app/admin/operators/new': typeof AppAdminOperatorsNewRoute
  '/_app/admin/riders/$id': typeof AppAdminRidersIdRouteWithChildren
  '/_app/admin/riders/new': typeof AppAdminRidersNewRoute
  '/_app/admin/sites/$id': typeof AppAdminSitesIdRouteWithChildren
  '/_app/admin/sites/new': typeof AppAdminSitesNewRoute
  '/_app/admin/coaches/': typeof AppAdminCoachesIndexRoute
  '/_app/admin/operators/': typeof AppAdminOperatorsIndexRoute
  '/_app/admin/riders/': typeof AppAdminRidersIndexRoute
  '/_app/admin/sites/': typeof AppAdminSitesIndexRoute
  '/_app/admin/coaches/$d/view': typeof AppAdminCoachesDViewRoute
  '/_app/admin/coaches/$id/edit': typeof AppAdminCoachesIdEditRoute
  '/_app/admin/operators/$id/edit': typeof AppAdminOperatorsIdEditRoute
  '/_app/admin/operators/$id/view': typeof AppAdminOperatorsIdViewRoute
  '/_app/admin/riders/$id/view': typeof AppAdminRidersIdViewRoute
  '/_app/admin/sites/$id/view': typeof AppAdminSitesIdViewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/admin'
    | '/dashboard'
    | '/changePassword'
    | '/forgotPassword'
    | '/signIn'
    | '/signUp'
    | '/admin/coaches/new'
    | '/admin/operators/new'
    | '/admin/riders/$id'
    | '/admin/riders/new'
    | '/admin/sites/$id'
    | '/admin/sites/new'
    | '/admin/coaches'
    | '/admin/operators'
    | '/admin/riders'
    | '/admin/sites'
    | '/admin/coaches/$d/view'
    | '/admin/coaches/$id/edit'
    | '/admin/operators/$id/edit'
    | '/admin/operators/$id/view'
    | '/admin/riders/$id/view'
    | '/admin/sites/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/admin'
    | '/dashboard'
    | '/changePassword'
    | '/forgotPassword'
    | '/signIn'
    | '/signUp'
    | '/admin/coaches/new'
    | '/admin/operators/new'
    | '/admin/riders/$id'
    | '/admin/riders/new'
    | '/admin/sites/$id'
    | '/admin/sites/new'
    | '/admin/coaches'
    | '/admin/operators'
    | '/admin/riders'
    | '/admin/sites'
    | '/admin/coaches/$d/view'
    | '/admin/coaches/$id/edit'
    | '/admin/operators/$id/edit'
    | '/admin/operators/$id/view'
    | '/admin/riders/$id/view'
    | '/admin/sites/$id/view'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_auth/changePassword'
    | '/_auth/forgotPassword'
    | '/_auth/signIn'
    | '/_auth/signUp'
    | '/_app/admin/coaches/new'
    | '/_app/admin/operators/new'
    | '/_app/admin/riders/$id'
    | '/_app/admin/riders/new'
    | '/_app/admin/sites/$id'
    | '/_app/admin/sites/new'
    | '/_app/admin/coaches/'
    | '/_app/admin/operators/'
    | '/_app/admin/riders/'
    | '/_app/admin/sites/'
    | '/_app/admin/coaches/$d/view'
    | '/_app/admin/coaches/$id/edit'
    | '/_app/admin/operators/$id/edit'
    | '/_app/admin/operators/$id/view'
    | '/_app/admin/riders/$id/view'
    | '/_app/admin/sites/$id/view'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_auth/changePassword",
        "/_auth/forgotPassword",
        "/_auth/signIn",
        "/_auth/signUp"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/admin",
        "/_app/dashboard"
      ]
    },
    "/_app/admin": {
      "filePath": "_app/admin.tsx",
      "parent": "/_app",
      "children": [
        "/_app/admin/coaches/new",
        "/_app/admin/operators/new",
        "/_app/admin/riders/$id",
        "/_app/admin/riders/new",
        "/_app/admin/sites/$id",
        "/_app/admin/sites/new",
        "/_app/admin/coaches/",
        "/_app/admin/operators/",
        "/_app/admin/riders/",
        "/_app/admin/sites/",
        "/_app/admin/coaches/$d/view",
        "/_app/admin/coaches/$id/edit",
        "/_app/admin/operators/$id/edit",
        "/_app/admin/operators/$id/view"
      ]
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/_auth/changePassword": {
      "filePath": "_auth/changePassword.tsx"
    },
    "/_auth/forgotPassword": {
      "filePath": "_auth/forgotPassword.tsx"
    },
    "/_auth/signIn": {
      "filePath": "_auth/signIn.tsx"
    },
    "/_auth/signUp": {
      "filePath": "_auth/signUp.tsx"
    },
    "/_app/admin/coaches/new": {
      "filePath": "_app/admin/coaches/new.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/operators/new": {
      "filePath": "_app/admin/operators/new.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/riders/$id": {
      "filePath": "_app/admin/riders/$id.tsx",
      "parent": "/_app/admin",
      "children": [
        "/_app/admin/riders/$id/view"
      ]
    },
    "/_app/admin/riders/new": {
      "filePath": "_app/admin/riders/new.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/sites/$id": {
      "filePath": "_app/admin/sites/$id.tsx",
      "parent": "/_app/admin",
      "children": [
        "/_app/admin/sites/$id/view"
      ]
    },
    "/_app/admin/sites/new": {
      "filePath": "_app/admin/sites/new.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/coaches/": {
      "filePath": "_app/admin/coaches/index.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/operators/": {
      "filePath": "_app/admin/operators/index.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/riders/": {
      "filePath": "_app/admin/riders/index.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/sites/": {
      "filePath": "_app/admin/sites/index.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/coaches/$d/view": {
      "filePath": "_app/admin/coaches/$d.view.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/coaches/$id/edit": {
      "filePath": "_app/admin/coaches/$id.edit.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/operators/$id/edit": {
      "filePath": "_app/admin/operators/$id.edit.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/operators/$id/view": {
      "filePath": "_app/admin/operators/$id.view.tsx",
      "parent": "/_app/admin"
    },
    "/_app/admin/riders/$id/view": {
      "filePath": "_app/admin/riders/$id.view.tsx",
      "parent": "/_app/admin/riders/$id"
    },
    "/_app/admin/sites/$id/view": {
      "filePath": "_app/admin/sites/$id.view.tsx",
      "parent": "/_app/admin/sites/$id"
    }
  }
}
ROUTE_MANIFEST_END */
