<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Blocks/Application/Application.csproj" />
    <ProjectReference Include="../Domain/Dummy.Domain.csproj" />
  </ItemGroup>

</Project>
