<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Common\Common.csproj" />
  </ItemGroup>

</Project>
