<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>$(DefaultAssemblyName)</AssemblyName>
    <RootNamespace>$(DefaultRootNamespace)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Blocks\Persistence.Cosmos\Persistence.Cosmos.csproj" />
    <ProjectReference Include="..\Domain\Dummy.Domain.csproj" />
  </ItemGroup>

</Project>
